apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer
  namespace: example-system
  labels:
    run: my-loadbalancer
spec:
  ports:
    - port: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    run: my-loadbala